import { writeFileSync } from "node:fs";
import { join } from "node:path";
import type { EnvSchema } from "./types.js";

/**
 * Options for markdown generation
 */
export interface GenerateMarkdownOptions {
  /** Output file name (default: ENVIRONMENT.md) */
  outputFile?: string;
  /** Working directory (default: process.cwd()) */
  cwd?: string;
  /** Title for the markdown document */
  title?: string;
  /** Whether to include a table of contents */
  includeToc?: boolean;
}

/**
 * Escape pipe characters for markdown tables
 */
function escapeMarkdown(str: string): string {
  return str.replace(/\|/g, "\\|").replace(/\n/g, " ");
}

/**
 * Generate markdown documentation from an environment schema
 *
 * @param schema - The environment variable schema
 * @param options - Generation options
 * @returns The generated markdown string
 *
 * @example
 * ```ts
 * import { generateMarkdown } from "envguard";
 *
 * const schema = {
 *   DATABASE_URL: { required: true, description: "Database connection" }
 * };
 *
 * const markdown = generateMarkdown(schema);
 * ```
 */
export function generateMarkdown(
  schema: EnvSchema,
  options: GenerateMarkdownOptions = {}
): string {
  const { title = "Environment Variables" } = options;

  const lines: string[] = [];

  // Title
  lines.push(`# ${title}`);
  lines.push("");
  lines.push(
    "This document describes all environment variables used by this application."
  );
  lines.push("");
  lines.push(
    "> 📝 This file was auto-generated by [envguard](https://www.npmjs.com/package/envguard)"
  );
  lines.push("");

  // Table header
  lines.push(
    "| Name | Required | Default | Description | Example |"
  );
  lines.push(
    "|------|----------|---------|-------------|---------|"
  );

  // Table rows
  for (const [name, config] of Object.entries(schema)) {
    const required = config.required === true ? "✅" : "❌";
    const defaultValue = config.default ?? "—";
    const description = config.description
      ? escapeMarkdown(config.description)
      : "—";
    const example = config.example ? escapeMarkdown(config.example) : "—";

    lines.push(
      `| \`${name}\` | ${required} | \`${defaultValue}\` | ${description} | ${example} |`
    );
  }

  lines.push("");

  // Add allowed values section if any exist
  const varsWithAllowed = Object.entries(schema).filter(
    ([, config]) => config.allowed && config.allowed.length > 0
  );

  if (varsWithAllowed.length > 0) {
    lines.push("## Allowed Values");
    lines.push("");

    for (const [name, config] of varsWithAllowed) {
      lines.push(`### \`${name}\``);
      lines.push("");
      if (config.allowed) {
        for (const value of config.allowed) {
          lines.push(`- \`${value}\``);
        }
      }
      lines.push("");
    }
  }

  // Footer
  lines.push("---");
  lines.push("");
  lines.push(
    `*Generated on ${new Date().toISOString().split("T")[0]}*`
  );
  lines.push("");

  return lines.join("\n");
}

/**
 * Generate and write markdown documentation to a file
 *
 * @param schema - The environment variable schema
 * @param options - Generation options
 * @returns The path to the generated file
 */
export function writeMarkdown(
  schema: EnvSchema,
  options: GenerateMarkdownOptions = {}
): string {
  const { outputFile = "ENVIRONMENT.md", cwd = process.cwd() } = options;

  const markdown = generateMarkdown(schema, options);
  const outputPath = join(cwd, outputFile);

  writeFileSync(outputPath, markdown, "utf-8");

  return outputPath;
}
