import { writeFileSync } from "node:fs";
import { join } from "node:path";
import type { EnvSchema } from "./types.js";

/**
 * Options for .env.example generation
 */
export interface GenerateEnvExampleOptions {
  /** Output file name (default: .env.example) */
  outputFile?: string;
  /** Working directory (default: process.cwd()) */
  cwd?: string;
  /** Whether to include comments with descriptions */
  includeComments?: boolean;
  /** Whether to group required and optional variables */
  groupByRequired?: boolean;
}

/**
 * Generate .env.example content from an environment schema
 *
 * @param schema - The environment variable schema
 * @param options - Generation options
 * @returns The generated .env.example content
 *
 * @example
 * ```ts
 * import { generateEnvExample } from "envguard";
 *
 * const schema = {
 *   DATABASE_URL: { required: true, description: "Database connection" },
 *   PORT: { required: false, default: "3000" }
 * };
 *
 * const content = generateEnvExample(schema);
 * // DATABASE_URL=
 * // PORT=3000
 * ```
 */
export function generateEnvExample(
  schema: EnvSchema,
  options: GenerateEnvExampleOptions = {}
): string {
  const { includeComments = true, groupByRequired = false } = options;

  const lines: string[] = [];

  // Header comment
  lines.push("# Environment Variables");
  lines.push("# Generated by envguard - https://www.npmjs.com/package/envguard");
  lines.push("#");
  lines.push("# Copy this file to .env and fill in the values");
  lines.push("");

  const entries = Object.entries(schema);

  if (groupByRequired) {
    // Group by required/optional
    const required = entries.filter(([, config]) => config.required === true);
    const optional = entries.filter(([, config]) => config.required !== true);

    if (required.length > 0) {
      lines.push("# ============================================");
      lines.push("# Required Variables");
      lines.push("# ============================================");
      lines.push("");

      for (const [name, config] of required) {
        lines.push(...generateEnvLine(name, config, includeComments));
      }
    }

    if (optional.length > 0) {
      lines.push("# ============================================");
      lines.push("# Optional Variables");
      lines.push("# ============================================");
      lines.push("");

      for (const [name, config] of optional) {
        lines.push(...generateEnvLine(name, config, includeComments));
      }
    }
  } else {
    // No grouping, just list all
    for (const [name, config] of entries) {
      lines.push(...generateEnvLine(name, config, includeComments));
    }
  }

  return lines.join("\n");
}

/**
 * Generate lines for a single environment variable
 */
function generateEnvLine(
  name: string,
  config: EnvSchema[string],
  includeComments: boolean
): string[] {
  const lines: string[] = [];

  if (includeComments) {
    // Add description comment
    if (config.description) {
      lines.push(`# ${config.description}`);
    }

    // Add allowed values comment
    if (config.allowed && config.allowed.length > 0) {
      lines.push(`# Allowed values: ${config.allowed.join(", ")}`);
    }

    // Add required indicator
    if (config.required === true) {
      lines.push("# [REQUIRED]");
    }
  }

  // The actual env variable line
  const value = config.default ?? (config.example ?? "");
  lines.push(`${name}=${value}`);
  lines.push("");

  return lines;
}

/**
 * Generate and write .env.example file
 *
 * @param schema - The environment variable schema
 * @param options - Generation options
 * @returns The path to the generated file
 */
export function writeEnvExample(
  schema: EnvSchema,
  options: GenerateEnvExampleOptions = {}
): string {
  const { outputFile = ".env.example", cwd = process.cwd() } = options;

  const content = generateEnvExample(schema, options);
  const outputPath = join(cwd, outputFile);

  writeFileSync(outputPath, content, "utf-8");

  return outputPath;
}
